// IMPORTANT: This file needs to be auto-generated by FlutterFire CLI
// Follow steps below to generate it

import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRa_aECUp94RiCd3M1azzdcsPFCnCGBw',
    appId: '1:92549361148:android:e10335554d63bd2d3c9679',
    messagingSenderId: '92549361148',
    projectId: 'eldersafe-16e15',
    storageBucket: 'eldersafe-16e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.eldercare.monitoring',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    authDomain: 'YOUR_AUTH_DOMAIN',
  );
}

// TO GENERATE THIS FILE:
// 1. Install FlutterFire CLI: flutter pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. Select your Firebase project
// 4. Select platforms: Android, iOS (Web optional)
// 5. This file will be auto-generated with correct values